version: "3.8"
services:
  vault-server:
    build: .
    container_name: vault_vault-server_1
    restart: always
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./config:/vault/config
      - ./raft:/vault/raft
      - ./policies:/vault/policies
      - ./logs:/vault/logs
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_API_ADDR=${VAULT_ADDR}
      - VAULT_ADDRESS=${VAULT_ADDR}
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    
